=== Vibishna17/Gift-shop/test1.xsd
<?xml version="1.0"?>
            <xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
                <xs:element name="cakeorder">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="order" minOccurs="1" maxOccurs="unbounded">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="name" type="xs:string"/>
                                        <xs:element name="price">
                                            <xs:simpleType>
                                                <xs:restriction base="xs:integer">
                                                    <xs:minInclusive value="100"></xs:minInclusive>
                                                    <xs:maxExclusive value="2000"></xs:maxExclusive>
                                                </xs:restriction>
                                            </xs:simpleType>
                                        </xs:element>
                                        <xs:element name="baker" type="xs:string"/>
                                        <xs:element name="status" type="xs:string"/>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:schema>

=== Vibishna17/Gift-shop/order.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet href="order.xsl" type="text/xsl" ?>

<cakeorder xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="test1.xsd">
    <order>
        <name>whiteforest</name>
        <price>600</price>
        <baker>Chef ravi</baker>
        <status> shipping</status>
    </order>
<order>
        <name>black forest</name>
        <price>450</price>
        <baker> Chef Karu</baker>
        <status>packed</status>
    </order>
    <order>
        <name>Rainbow </name>
        <price>1000</price>
        <baker>Chef Gur</baker>
        <status>Delivered</status>
    </order>
    <order>
        <name>Blue current</name>
        <price>800</price>
        <baker>Chef nana</baker>
        <status>packed</status>
    </order>
    <order>
        <name>redvelvet</name>
        <price>200</price>
        <baker> Chef harry</baker>
        <status>Delivered</status>
    </order>
</cakeorder>
